### GENERAL SETTINGS ###

# Site settings
title: Visual Studio Geeks
description: "24x7 Visual Studio Geeks"
analytics: UA-57919718-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: /test-it
url: "http://www.visualstudiogeeks.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
highlighter: pygments
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: http://www.twitter.com/onlyutkarsh
  - title: twitter
    url: http://www.twitter.com/arora_tarun
  
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - United Kingdom.
email: visualstudiogeeks@gmail.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Utkarsh Shigihalli
    position: 
    text: Microsoft MVP | Microsoft ALM Ranger
    img: utkarsh_240x240.png
    social:
      #- title: Private Blog
      #  url: 
      - title: twitter
        url: http://twitter.com/onlyutkarsh
  - name: Tarun Arora
    position: 
    text: Microsoft MVP | Microsoft ALM Ranger
    img: tarun_240x240.jpeg
    social:
      #- title: envelope #use for email address
      #  url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/arora_tarun
    
# Clients information. Shown on Home and About pages.
#clients:
#  - name: dribbble
#    img: client01.png
#  - name: Code is Poetry
#    img: client02.png
#  - name: Vimeo
#    img: client03.png
#  - name: VimeoPro
#    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Friends collaborating and discussing technology over a coffee. This is our site, showcasing our work together."

# Testimonial content. Shown on Home and About page. 
#testimonial:
#    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
 #   author: Marcel Newman
 #   position: WEB DESIGNER - BLACKTIE.CO
